#!/usr/bin/env bash
# The script below will help me group visitors by IP and HTTP status code, and display the data using awk and no loops

awk '{print $1, $9}' | awk '{count[$1, $2]++} END {for (i in count) print count[i], i}' | sort -nr | awk '{printf "%s %s %s\n", $1, $2, $3}'
