#!/usr/bin/env bash
# The script below will help me group visitors by IP and HTTP status code, and display the data using awk and no loops

awk '{print $1, $9}' apache-access.log | sort | uniq -c | awk '{printf "%s %s\n", $2, $3}'
