#!/usr/bin/env bash
# The script below is to loop from 1 to 10, but in the forth position, we echo 4th iteration, and good luck for the other ones, then I display 'Best School' for the other stuff.
i=1
while (( i <= 10 ))
do
	if (( i == 4 ))
	then
		echo "bad luck"
	elif (( i == 8 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
