#!/usr/bin/env bash
# the script below is used to display time in hours and minutes using a while loop

hour=0
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]; do
        echo $minute
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done

