#!/usr/bin/env bash
# The script below will manage processes/daemons running in the terminal

case $1 in
    start)
        nohup /path/to/manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        nohup /path/to/manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
